'''
As we all know, a palindrome is a word that equals its reverse. Here are some examples of palindromes: malayalam, gag, appa, amma.

We consider any sequence consisting of the letters of the English alphabet to be a word. So axxb,abbba and bbbccddx are words for our purpose. And aaabbaaa, abbba and bbb are examples of palindromes.

By a subword of a word, we mean a contiguous subsequence of the word. For example the subwords of the word abbba are a, b, ab, bb, ba, abb, bbb, bba, abbb, bbba and abbba.

In this task you will given a word and you must find the longest subword of this word that is also a palindrome.

For example if the given word is abbba then the answer is abbba. If the given word is abcbcabbacba then the answer is bcabbacb.

Solution hint
Any subword of w that is a palindrome is also a subword when w is reversed.

Input format
The first line of the input contains a single integer N indicating the length of the word. The following line contains a single word of length N, made up of the letters a,b,…, z.

Output format
The first line of the output must contain a single integer indicating the length of the longest subword of the given word that is a palindrome. The second line must contain a subword that is a palindrome and which of maximum length. If there is more than one subword palindrome of maximum length, print the one that is lexicographically smallest (i.e., smallest in dictionary order).

Test Data:
You may assume that 1 ≤ N ≤ 5000. You may further assume that in 30% of the inputs 1 ≤ N ≤ 300.

Example:
We illustrate the input and output format using the above examples:

Sample Input 1:
5
abbba
Sample Output 1:
5
abbba
Sample Input 2:
12
abcbcabbacba
Sample Output 2:
8
bcabbacb
Sample Test Cases
Input	Output
Test Case 1	
5
abbba
5
abbba
Test Case 2	
12
abcbcabbacba
8
bcabbacb
Test Case 3	
12
abcbcabbacba
8
bcabbacb
Test Case 4	
50
tnautwzhfcsqesmrayxqknytkktynkqxyarmseqscfhzwtuant
50
tnautwzhfcsqesmrayxqknytkktynkqxyarmseqscfhzwtuant
Test Case 5	
280
ofntcsgzvdfzqlvuipipydmzpsgvdwxrdmlfetebwjdowylgotvowhnlavifrhwwuhbadhczqhqofbwvwrmubbhdxpiqwensoottwxuoekflnbjjvvdywkbtblkyrzqhnlalkvcqfjcvklehikfewiayvkynjquyevmoomveyuqjnykvyaiqqhxzjslwztglakjjkhgwhthaoieluudmbalmvwiwrqhsbqdnajmjdvjtdpgzkjlllwyiviemznecejrgtdrybbteqbgakroxqmgl
30
iayvkynjquyevmoomveyuqjnykvyai
Test Case 6	
800
tfbkfefsghlrnpiqurtxisosaizbhnkcsmpxquszcfsrvahprcpbvdtxlvyuilzaxoapisqmzjdujnmdrbemgaktvkodvpfudfmnzcablfvxujcmkgaqimmdxaiuporuvdhxfjytpvqlfuxpaailmuqlwzgnpxhkcohjyhcpducioczrchcodsaztioihvtjkcskkxbprfxihwzjgdylxalribzrxuajxuvjryaldzvlxuudzupwucpedpvclxlkugvnevykutvsprxqmopiqepwvmahmmrguntbiulfpixhzuxljmwbtlzoxavjoprkcllmfyrwgqdgnbtwppziabzadultldltludazbaizppwtbngdqgwryfmllckrpojvaxozltbwmjlxuzhdnorcvpvtymxgzazxppyarzzrevdxhgbwwsytjumjijphlpedgedxeerkzwigcjfaddtozhahtpoeguhozmofqfpsbzafkffpjaeijescvgjedssefglxlcpocstmxaeicitmolqltzpwuiabonycqqquimghmkqpujdkutypvnmpxoqocqqugioquwyjhqadbdqxwomtdyibpyptphnxrbqmxqxggxmjacgysssvtayibpbswqrqrhcqxbxfyloynwyhpqeitfswuvotlhjepnuoorwmcmmrjkaydfiymcugxkzkrkoixixncvzghnyqaaqfhydtcxazjblaozlnikbmfcsmqsfstvxawawyzyaiblkpnxdxhgjoibbauispfrrbtncslccnppe
101
hzuxljmwbtlzoxavjoprkcllmfyrwgqdgnbtwppziabzadultldltludazbaizppwtbngdqgwryfmllckrpojvaxozltbwmjlxuzh
Test Case 7	
1500
hiuuedvipfzkkreondlpchyzwvoyvblclfyriuzabakorrcgunywwyyutouopfqckrttnuvqufeoyiwtvurttromfkdwqvyamtvznqqkyuyydwratlwmcmakwdgmzhpnckpqdfadbabgyvjrghfktiupndemmtcofrgkyipzktijotcwaigtsdkfiosujwkrnrdlztmkmuvcpxyphgizjtfrjznvvymkrrvqmjcygxcvxalgjtiuonoaobvlbjxsasjnbnnhnqdksqsdjayapmafnxqpgnjihuxlinuvdzhxpzbbczbrldxacpridbsmvqzffuaivjhnlkonlreywbzyrsiwvakrskwzgzhdirqtdggpxnnvqothhdfcgqvacuakvjnfagzemhtkwihnxbwgeckkuilyclizwxexdddsnyelglyfovltzyftgstkfdjcanbgteyicctkpsqepdzobejhzctgfckhqlpjrnrvrmghgynvbmlfquoryiydkkncwcnnsgljtrszrfxuribkfqddadjkowpkyczsjkcedwfwecrxnshsklxkqgxeemqfqqxbcbhiyneerxbgsjacwypmgmtnajsszrwetdmtssxkqyskjtmftbubpnoryimaaietlsmeklqcjkmtdzaycuaujqnizzkbhouvgizstrvedhxhiyhnujjgcwqdwaefoaawibodslhwtffdfoqzyzhcyxfuxjznjcjtdawyldwgkbkrrcrreatcyyyvhzlqbujfwhdinzqzccrvfknjkgliflgokrhonstkayupzkodnfyupldcuqkbbspnjybxrwjtwdivpwaeczytmdvgtijwazmmxplqmujizrgqogvsftnuzlauvkrvlfjkuubiqmrpexgufdonwdhxqjslvljgqstknwtfkmvoldkqgadegmcwwuirfravlvharcgbqbsbgeumhzqnmslkotbtmdqyyayreevvhnyntubcusrimdsbyvwlzplxplptskozzppujqxdkonztfcsdyfcnqzedqyvcovddmypcxupniohpqbsogueywkbmkxrzuuegutktobhypqnfrgwxccvymynxvgypaexxakqqlzobpbigjgfoicmxbbwyhuokanjazzqlzeooiwxtdehnhwkixgghcwtdmcfldwyccmtmlqgqunddlqnlywsbsnggplssjsxmfqasigiewnkhfxsetmfoznuqaolkhiyoaygkfqqdfaklyfpttwhvlcllsyvzitpisxuznlevnoonvelnzuxsiptizvysllclvhwttpfylkafdqqfkgyaoyihkloaqunzofmtesxfhknweigisaqfmxsjsslpggnsbswylnqlddnuqggnvxhpvomgsxrlwpmgiepcbldrwhmmyuzvrgmoxyurwneuctanxrryfvpbebpcvpyoxkcwjyohmsdolfdizvjeqyhwcxzzozollsi
200
gqunddlqnlywsbsnggplssjsxmfqasigiewnkhfxsetmfoznuqaolkhiyoaygkfqqdfaklyfpttwhvlcllsyvzitpisxuznlevnoonvelnzuxsiptizvysllclvhwttpfylkafdqqfkgyaoyihkloaqunzofmtesxfhknweigisaqfmxsjsslpggnsbswylnqlddnuqg
Test Case 8	
2000
jnrofbluttxmxhgesbyjhhwdkmyppnhybapgeacxwblvjrbbvzmcjkitygkptspwueeyhjvfkhavacyxbkamwkfuqqjlkbkefodoxatkjwfkyehbqjqnvvhlntzxujebzhqzjjjthodhumjlyzytwhhkcihwtlasuqtebcxjtcqpqbaqcakzitlkbujuijocziicmhnhlexehxukyglizyscsdwamnfnxpsjxfrklqotnjfnpsvrqqtktslifsxehpngvgtgwhbmsgzkaxbspwdioosviqzrfpyaxrjwakittjftiioxerivhaspqugylgaizjeawovraamiiagorqlyqepjywjjejtevaerobkqbwzlxhbqxnppreyrchchtvlovrhmsrcvndgmgdnvcrsmhrvolvthchcryerppnxqbhxlzwbqkboreavetjejjwyjpeqylqrogaiimaarvowaejziaglyguqpsahvirexoiitfjttikawjrxaypfrzqivsooidwpsbxakzgsmbhwgtgvgnphexsfilstktqqrvspnfjntoqlkrfxjspxnfnmawdscsyzilgykuxhexelhkjdjwszpyzidjkkcixsfozrgqwbfzjsmsvvrpwgnypqhbcljzdppcixseazgjrsempvdodtmujtwoehnjwflfcflderoylumbpqrvjdpuynievyntdyyhfmklfbjrvwunmlivqzropaskahdfhemmqzxxahovfiirvsolufbjhvtjcyolcbxuaxsagixltieoaucubddlzyudxjpbmoyolqqtangtvkiyemsipytqynuvwjxkzxylnogpcnjzztxefsmuqflouhmtqldpiecxslmwyxyxqvdvnrsfydwtmkmevrvfvycqlqojomiekoczfufgzdblnppkgkpektuvjkgzxrehfigmcnsbqtofifrrpgvczrzlbikazqhgyqsadndwitdtyvkqbhudatqddaectnkrdfujszhatkttffjjmdoozescgwhzlrrrwnaqmhrhtmbbukmiqaxpgprmnymysfpqsrheaaouopxibjrrlqgrfaduaruuwmlqdsxgslcgazrbiittybmfdpbejvyfhlwndttxgveguvjefezfglmlcnrlistsdrfhmyesvkarhjvoowtwjhhluzzfruxuncdzcktzutqcelssjmqstyfqzgvsauonyuoaejzyercjevdnjufeumwttrntnbjlvznbjoanfeyjbcwmwdrsqnllhaeudpibpvcakeppjozmsxzodqivfvgovmlyctztocvagkqraresqditvqoclurijehlxignmdovngmqzsipxtlujbxxyqfhuoutxcglfwgsevkdptvnmihxjgwjwcqssmlroudtsloziyeytbnhjwfvddebhxuajhradwtyijxsibqbddjoaqlfvqgdpcdakwcpvwpdhmxpqotvtejtwxarphwejzgvyjnthcyorvghlzcffnabmbubkrftsorsxelgiluzjagubkzgacjmfgqpxvkrlbkkhxqqjlrsnaorkqxmsjbxproooyhacrkjrdbcqtwdvkufauuufvtwohmcgteinrteuxgkscpnomuriolnlhjbovewqkgdbajxzpjrtzgklabtroievtgkqmggwpmarvxqnhjiipsvrtqkkypftxrjjyrhpdhgbhwoqfyywrtpmjawjrecovnzvegkkqqlxmbntbnrsghhrjfacjesfrravznhpdumqvblzodrwmanxgpbrttymmbklordrmpjjtvihaceoctnkjocejcrxdbkrunlgfusyrchtelhjhwvqkzwvcnufqfzluktzenzwqhrwuzhbvdticqfefamwhljbvedbsczklrggsqjptdxxvfeahqyodjpaosbixbsisaqmqcbjfbhcglcndddgmsganjimmcwgdpsvruhyvq
401
hlexehxukyglizyscsdwamnfnxpsjxfrklqotnjfnpsvrqqtktslifsxehpngvgtgwhbmsgzkaxbspwdioosviqzrfpyaxrjwakittjftiioxerivhaspqugylgaizjeawovraamiiagorqlyqepjywjjejtevaerobkqbwzlxhbqxnppreyrchchtvlovrhmsrcvndgmgdnvcrsmhrvolvthchcryerppnxqbhxlzwbqkboreavetjejjwyjpeqylqrogaiimaarvowaejziaglyguqpsahvirexoiitfjttikawjrxaypfrzqivsooidwpsbxakzgsmbhwgtgvgnphexsfilstktqqrvspnfjntoqlkrfxjspxnfnmawdscsyzilgykuxhexelh
Test Case 9	
1000
qfqnvhtczmegaalgozmlgvbkvxvjbisupjhmsbotpuzrxmxlnlytjaggzbpblkxcteonhegyafpxtokgcjallgtkjinwskynroaasgzunqsihcpjnrwazplkzagslehesiemqfggwaofffouymvxbihaiputtcznmebcjikhkzmpgckfofernosxdotzqsmewqhiytpkseabgkixrmogcidgzwfprtunjdxjwnurtusbgcyzopfrzkzyjeoazkpjpnuncogvkawscxrtoyknjlmupcuqojzfwwsykzvxbupetjxhhjusugmligbysddozwplxmkaiaebldisodnilzvwixuacyqdwhqvwbvedagofoguttcfvabdxvfbvxerfwmbxifaknqpczjvuoapodunzzowxuoeqahqkoqucjmeivbcjeszhomiocfnwttpvafiqxcsgqyomatxelznzlwpobemwzdtbibsigkqwlhklairljgmucekfkzbkcvlnydveqnbbulouvhhenubsanxkmbupyiewlzbddbzlweiypubmkxnasbunehhvuolubbnqevdynlvckbzkfkecumgjlrialkhlwqkgisbibtdzwmebopwlznzlextamoyqgscxqifavpttwnfcoimohzsejcbviemjcuqokqhaqeouxwozznudopaouvjzcpqnkafixbmwfrexvbfvxdbavfcttugofogadevbwvqhwdqycauxiwvzlindosidlbeaiakmxlpwzoddsybgilmgusujhhxjteoegjrudpdlvthwlhkkrylonjwrijsjnhpvqisvxvgvontbwdmoexetjalrjfcyotugboczjkwaapbwvnmznqswsfpclrcbkyinmmowwkyyabxvpluecmausryfidgubqhocwmbgkbilydckxgomikgblnjotfpmpdqnrtvdvepvhthhcvvmibotozhjhwxwcojthexeko
500
etjxhhjusugmligbysddozwplxmkaiaebldisodnilzvwixuacyqdwhqvwbvedagofoguttcfvabdxvfbvxerfwmbxifaknqpczjvuoapodunzzowxuoeqahqkoqucjmeivbcjeszhomiocfnwttpvafiqxcsgqyomatxelznzlwpobemwzdtbibsigkqwlhklairljgmucekfkzbkcvlnydveqnbbulouvhhenubsanxkmbupyiewlzbddbzlweiypubmkxnasbunehhvuolubbnqevdynlvckbzkfkecumgjlrialkhlwqkgisbibtdzwmebopwlznzlextamoyqgscxqifavpttwnfcoimohzsejcbviemjcuqokqhaqeouxwozznudopaouvjzcpqnkafixbmwfrexvbfvxdbavfcttugofogadevbwvqhwdqycauxiwvzlindosidlbeaiakmxlpwzoddsybgilmgusujhhxjte
Test Case 10	
4500
rnnovornotoqxerkxoirodqnbtrrdfswsilpwcdkxtauxtfuipnysdmvwdmbkhacpnsnrvxoozjotqidhwbbbpzyslbcubhlobyfwxwmxhaszlvgjyhkoikiwmnqpucevcltchhbqktpxqxgohsepdnlpccewgktkyomhvnyfincylkpsdvjgivxkzdifodrorevpttucjzcwltqopzwzuvkvzuapyudryygtudxdeabptrgksekpawkzqnqqhtihtoanrysvatnvmtgfzsuzogagtqxalhhfviupipmiizfxuleudavtgwaaoxccgkjbufseufmfgrcbfixkiseoqeqhdtjjdumzzhdumrzskdvrlsctngjdmckrvvaarozrvenjvoehrzzeubzhjkkxmxohuqhmeifcmsljgprzrsflveseoedddrkyjumperrtlfctwvsnpzykfsqvztycmjcvfoljhecslhliefvuewejqxfpqdudowatnlfusjndqylxgjrkhxuzubplelqvhsqwgvryfgdxgpumanxjltihuzuakmvufmqlhjjopmowdkifyholcxuwwpxhbsdigtttgidsbhxpwwuxclohyfikdwompojjhlqmfuvmkauzuhitljxnamupgxdgfyrvgwqshvqlelpbuzuxhkrjgxlyqdnjsuflntawodudqpfxqjeweuvfeilhlscehjlofvcjmcytzvqsfkyzpnsvwtcfltrrepmujykrdddeoesevlfsrzrpgjlsmcfiemhquhoxmxkkjhzbuezzrheovjnevrzoraavvrkcmdjgntcslrvdkszrmudhzzmudjjtdhqeqoesikxifbcrgfmfuesfubjkgccxoaawgtvadueluxfziimpipuivfhhlaxqtgagozuszfgtmvntavsyrnaothithqqnqzkwapkeskgrtpbaedxdutgyyrduypauzvkvuzwzpoqtlwczjcuttpverordofidzkxvigjvdspklycnifynvhmoyktkgweccplndpeshogxqxptkqbhhctlcvecupqnmwikiokhyjgvlzsahxmwxwfqdeesruqwfbcfkqsnpojmdivhdypjtlzwpgricjfjkjqvzkkrztfeeanjafstqusfcloguvqheicftowsjbwndkwdrrzhnrorcexyzpffyjlrxhlhlhuottsmmrtzkksoormqhuvhdgybqjkbsepozjancwomggcwypmhjkooqopixzjrgbhhkivngjbmsekqvxzghnwzboiantrvubfhjcwrnxdfdnxamwivjfvmvfokyigvjncupylcxqkdfhfseqnpxkespscqakljxndonotmedrkkxeontgkekeveglfrwqqlufakynrbedndhesckegwieapphioaybwfegdtzgzcudlyxokcwgkaibssjiskloprwvkwbmaxpovmchoanbdycxsmhmwuanmyiywkkxjbnhoroerehwcktwyciwxkjjisjfeuepvrwlklsbpzytltpjwzhtjretlnarjggfzdqjqilfklavgpfcqoxbfdustxlcdujdxampkzuumuqtlxxblvetayntvzybthesjshuudqgxibkhzntwrowrbsncqovzupjowfizvpygsknrxinqymicexeuncthrevqjerhvsnncchaluqlganmxsgkwcrnipfsvxzspohrqotdlmrrmeekymuuqoizdptamusdizxaqqgbexurbadanzwfnggswzsitmoboleebkfijzzmaeopdlutrbnnciywumzixdmaptiatjntpbktoeoghbvmjvigjhqgndjeytfrfumuxwnmddumfryqniwwsnfhsqlqjskomyjkvywacsojjnzwxyvpnawhqkzbcjqpibbfzzhdrvmaioziouxbwwiogjpkvhbdickkbrnumcxxswfgsejqatgicvtxfucpzozafpxututlsatmecchxirzfkzmhbcgqbixsftlbmytmrfrvjastruzetnlwprotboljhzkuxegplzkvbfotzpxudkqudhnevbncaayxgfmrgzmieddfuczzmpuryjxtmnymnwktdykmzzufezkablapbwibffvusvgfrsaxtnjuofasemshyuybqgcylzsgwalotonobyipfkjlxdsxysaqyeojgircjfsctfswdalklwvkznjzfjqfnervniyynqcgwucbupmhlhrnxcmelckbjbwyluwzlafjukmqbaypkrchuqnfvxigahembcnocuzyeooiomxyebharvhouquxxalacyrgssgzgvhvjevphdpyaxnunjtmkeooefxzydyeafbklxzsapsamhwbrspdydrdlqclucpwjtguqgosxgulosohkdklidqtuugqwwmfrtbhbpbavvllnbsageloibkevqutogyfbzoeopglkrxauraawnpgqbklrgggoensfcwvtdgewfgrzitxvkdllpydveljkabrcamyfuedckubsqynadamsyrpecyqcchhevhjplotvjupbuebxenpeegkihanjjwpedavooplzjaagecdkrvqybaiicvtltkrwkmmzbxanzbtffwrythyvhhflezwyjnuwcjxdixqialphihibogyynejufisqxomzxjfijxqjjhrrobufhvdxzorgyjwyzjzzuehdcxnlggevhaaqvfnwvecupbspmtogyvkcuzpahtxqvzgteupaauwsvqjhjznhwzjsaauhtsxrrgkyczyevuwqkfztgpdcoourppykhybaglyinymiulbesaazpfbgtwzinztwxwwfixnxvchqniwhjygadiixghhtjcriznojmdgifpauyycjxilcswbadjvonmxmclxoofyuvaqtzseydpavleyrptfcgcrinoycuxyrxomyjqwofzlrdjksdpwjsntherlaqjroadmltlzakktpudjztfknvduzwgznrsbtvpeqafsmqmbmpmlkuvxpauqwcpjvhmpecvwebortauhsjscdpcupyknabxvklmqpimwlangdjnxuhzzwdtnbfadgzbqnngcxuykxnsazfxtoyvmeozhucladotqdbtdwtnthgvinudcsyqypqgjutlxhgokijnecdxlluvyozciztholnxfgleprsbzbrfeuerfynfmmkvnfecsrbzzmdqgwrhzinfetxlumtgafdnmjpearfbfirlglvgvinadklxwggyllmxvbbxugzcrsnxdifzstbwfovevbcgnqekuhhoqgqhbgggqofjjihqxeusgzyvpehjmoaexsnyytepjmasujlrpflvgksyobjcqjgpetncpttahvveggvwnjtutoujpdofpuwtqjxhfrhoocsvkqryzkusyodotrviosdgdbnkuwzkbrflhyjgjdajtgznxxxnpbtueifafgmizsthqfpbksneymtxjqlatevxnczukmcjgxsyckcncptcdoznempytmxiozcalgktdcrgmtvqkquoewbiiqiddilthpwuvgnzkghzacrmumayidisutwzbhukxqesytrlzakbcbowpowxshqoampdvjnsctnamglnhxpjbdiqtgolngzpuqupahiecxeodsckptwqwgjpmxdcfetzvooxvybyxhobzslrljjjpszeregyizxfpocnodnmlbpmwcfhmprbjsfdwnbgpbmerorhsevfiktenzlbqeezwkeuzgbojntabmjvrfcbrwfgxshnxmmtytoxzrmkehmhvvfoajpshuyenirkugfszvramfksmwckrhyuqooyimexuwjqeridmadbfpvulxeegcaxsoxbbdaxzkodbyipalsicocpliusmurfjqimtilvuzyvajnawfiztmohukzjfsoqiwedgpybrzyriltetedmqstncuwjmmbwifaqxyroxqhhdamweplxjgkobizpuboeioufomtoecvhfhgjzrgixsyyayquzeajuvpkjkannwwsfcdgtmrreprhnjbopeylzpwizyxowticwmkpybietclglpxbtxmsmkcnjzcfskjqwuiwvqbosmxedwhwttqhgsuprwumjgcfakexdfoxtndzjkvegmlmghbagxmpdqufdadgfrdbejaptxvblgnspqsvqgkvyhbbhehnxnqdwsurpptbxivmbpirxsmvzpxhvgwsvoxtgrnxigyfqvsrkckhuzfwocfkkdegrebxxougwvlnsfgdhtmestcivjsimzoddrcagygcvurobatlthplbttycogonwtsovuuvbyrxshysajljaykvtjxhpnwmgqcdlwbowuloblidxtmztzvniuwzivnqlpwwnxkmrxaujlziglhamcpuxlwhijzubvsosfalcdhnogxuufwgj
1001
fwxwmxhaszlvgjyhkoikiwmnqpucevcltchhbqktpxqxgohsepdnlpccewgktkyomhvnyfincylkpsdvjgivxkzdifodrorevpttucjzcwltqopzwzuvkvzuapyudryygtudxdeabptrgksekpawkzqnqqhtihtoanrysvatnvmtgfzsuzogagtqxalhhfviupipmiizfxuleudavtgwaaoxccgkjbufseufmfgrcbfixkiseoqeqhdtjjdumzzhdumrzskdvrlsctngjdmckrvvaarozrvenjvoehrzzeubzhjkkxmxohuqhmeifcmsljgprzrsflveseoedddrkyjumperrtlfctwvsnpzykfsqvztycmjcvfoljhecslhliefvuewejqxfpqdudowatnlfusjndqylxgjrkhxuzubplelqvhsqwgvryfgdxgpumanxjltihuzuakmvufmqlhjjopmowdkifyholcxuwwpxhbsdigtttgidsbhxpwwuxclohyfikdwompojjhlqmfuvmkauzuhitljxnamupgxdgfyrvgwqshvqlelpbuzuxhkrjgxlyqdnjsuflntawodudqpfxqjeweuvfeilhlscehjlofvcjmcytzvqsfkyzpnsvwtcfltrrepmujykrdddeoesevlfsrzrpgjlsmcfiemhquhoxmxkkjhzbuezzrheovjnevrzoraavvrkcmdjgntcslrvdkszrmudhzzmudjjtdhqeqoesikxifbcrgfmfuesfubjkgccxoaawgtvadueluxfziimpipuivfhhlaxqtgagozuszfgtmvntavsyrnaothithqqnqzkwapkeskgrtpbaedxdutgyyrduypauzvkvuzwzpoqtlwczjcuttpverordofidzkxvigjvdspklycnifynvhmoyktkgweccplndpeshogxqxptkqbhhctlcvecupqnmwikiokhyjgvlzsahxmwxwf
Test Case 11	
2000
qmiqodqunuvkyupgtubirbthqxmfjaezmosatixgesqcmhiidlsxmmgelsluspwggoizwficzaeoiowncqkocqvnkgkcygkewtfuynwaocoyqkluayjfqgubmgfmoqskjyejncjdexbxjprmpcrhinixwqjkgcvrabapgmtklwhvlzhcbakkpsjliswquthwwkmcyhnjdwepvntzndlfyuqimozjhihgutiscxcguixrwqqlubqsvjakxbthkapewxzyxbgtjdkhwdtqelkcummuohbajqghpfioiohsuuzqxuibgsfaeruuaxwkpdrhizvrqflkzmayhizncfpiymdbjzlbeeipgfiwktglhijqsldusvcshhtsjevnldcrlkpxfxjpfufzfltzgxsphljqsffdkkwvwlteketryyqgjjfrizgplqhdvnihzedvrwzbcssatkictoudnctasafppnxotcmmalncghcbrldmbzqqcltwnyofonthpfurtjtbrxckkhznhrelczhrxxwlksvbxrssanttlxgvffjowpzaoitliqzsiuwhnqanevjptpkauvoskpsyxlmfdlalhyvuoxjuusjphwpdrfveupcudqbgbdukbresoomiiyyquptnvrtpgyljonssqocufjmtzydhybzuttkomdfsbreqgyiymmsrvemufpedtdymwicknhdpajhghrfvfxobeaxlrbomfoadycomktdmcmvlfaikzwlfylqpmfetvexwhnitgnhkbcxgcfqedejbpasdhwxedwamlkftzodarcgvjzzmdlnunfzweyahudthnaanofnfhwbqvccaprwcxvadwdkqgfatfaivgwdnuegriktacpebmfeiiqbovbjcdsxjqazkgfbrpurtlvuzcyikolylmknrcnbspceyhfpybisofoninvsbitpwdcohrpzhrdfakwangubljqtyoobwjqtovhxmywtwymxhvotqjwbooytqjlbugnawkafdrhzprhocdwptibsvninofosibypfhyecpsbncrnkmlylokiyczuvltruprbfgkzaqjxsdcjbvobqiiefmbepcatkirgeundwgviaftafgqkdwdavxcwrpaccvqbwhfnfonaanhtduhayewzfnunldmzzjvgcradoztfklmawdexwhdsapbjedeqfcgxcbkhngtinhwxevtefmpqlyflwzkiaflvmcmdtkmocydaofmobrlxaeboxfvfrhghjapdhnkciwmydtdepfumevrsmmyiygqerbsfdmokttuzbyhdyztmjfucoqssnojlygptrvntpuqyyiimooserbkudbgbqducpuevfrdpwhpjsuujxouvyhlaldfmlxyspksovuakptpjvenaqnhwuiszqiltioazpwojffvgxlttnassrxbvsklwxxrhzclerhnzhkkcxrbtjtrufphtnofoynwtlcqqzbmdlrbchgcnlammctoxnppfasatcnduotciktasscbzwrvdezhinvdhqlpgzirfjjgqyyrteketlwvwkkdffsqjlhpsxgztlfzfufpjxfxpklrcdlnvejsthhscvsudlsqjihlgtkwifgpieeblzjbdmyipfcnzihyamzklfqrvzihrdpkwxauureafsgbiuxqzuushoioifphgqjabhoummuckleqtdwhkdjtgbxyzxwepakhtbxkajvsqbulqqwrxiugcxcsitughihjzomiquyfldnztnvpewdjnhycmkwwhtuqwsiljspkkabchzlvhwlktmgpabarvcgkjqwxinihrcpmrpjxbxedjcnjeyjksqomfgmbugqfjyaulkqyocoawnyuftwekgyckgknvqcokqcnwoioeazcifwzioggwpsulslegmmxsldiihmcqsegxitasomzeajfmxqhtbributgpuykvunuqdoqimrbat
1995
miqodqunuvkyupgtubirbthqxmfjaezmosatixgesqcmhiidlsxmmgelsluspwggoizwficzaeoiowncqkocqvnkgkcygkewtfuynwaocoyqkluayjfqgubmgfmoqskjyejncjdexbxjprmpcrhinixwqjkgcvrabapgmtklwhvlzhcbakkpsjliswquthwwkmcyhnjdwepvntzndlfyuqimozjhihgutiscxcguixrwqqlubqsvjakxbthkapewxzyxbgtjdkhwdtqelkcummuohbajqghpfioiohsuuzqxuibgsfaeruuaxwkpdrhizvrqflkzmayhizncfpiymdbjzlbeeipgfiwktglhijqsldusvcshhtsjevnldcrlkpxfxjpfufzfltzgxsphljqsffdkkwvwlteketryyqgjjfrizgplqhdvnihzedvrwzbcssatkictoudnctasafppnxotcmmalncghcbrldmbzqqcltwnyofonthpfurtjtbrxckkhznhrelczhrxxwlksvbxrssanttlxgvffjowpzaoitliqzsiuwhnqanevjptpkauvoskpsyxlmfdlalhyvuoxjuusjphwpdrfveupcudqbgbdukbresoomiiyyquptnvrtpgyljonssqocufjmtzydhybzuttkomdfsbreqgyiymmsrvemufpedtdymwicknhdpajhghrfvfxobeaxlrbomfoadycomktdmcmvlfaikzwlfylqpmfetvexwhnitgnhkbcxgcfqedejbpasdhwxedwamlkftzodarcgvjzzmdlnunfzweyahudthnaanofnfhwbqvccaprwcxvadwdkqgfatfaivgwdnuegriktacpebmfeiiqbovbjcdsxjqazkgfbrpurtlvuzcyikolylmknrcnbspceyhfpybisofoninvsbitpwdcohrpzhrdfakwangubljqtyoobwjqtovhxmywtwymxhvotqjwbooytqjlbugnawkafdrhzprhocdwptibsvninofosibypfhyecpsbncrnkmlylokiyczuvltruprbfgkzaqjxsdcjbvobqiiefmbepcatkirgeundwgviaftafgqkdwdavxcwrpaccvqbwhfnfonaanhtduhayewzfnunldmzzjvgcradoztfklmawdexwhdsapbjedeqfcgxcbkhngtinhwxevtefmpqlyflwzkiaflvmcmdtkmocydaofmobrlxaeboxfvfrhghjapdhnkciwmydtdepfumevrsmmyiygqerbsfdmokttuzbyhdyztmjfucoqssnojlygptrvntpuqyyiimooserbkudbgbqducpuevfrdpwhpjsuujxouvyhlaldfmlxyspksovuakptpjvenaqnhwuiszqiltioazpwojffvgxlttnassrxbvsklwxxrhzclerhnzhkkcxrbtjtrufphtnofoynwtlcqqzbmdlrbchgcnlammctoxnppfasatcnduotciktasscbzwrvdezhinvdhqlpgzirfjjgqyyrteketlwvwkkdffsqjlhpsxgztlfzfufpjxfxpklrcdlnvejsthhscvsudlsqjihlgtkwifgpieeblzjbdmyipfcnzihyamzklfqrvzihrdpkwxauureafsgbiuxqzuushoioifphgqjabhoummuckleqtdwhkdjtgbxyzxwepakhtbxkajvsqbulqqwrxiugcxcsitughihjzomiquyfldnztnvpewdjnhycmkwwhtuqwsiljspkkabchzlvhwlktmgpabarvcgkjqwxinihrcpmrpjxbxedjcnjeyjksqomfgmbugqfjyaulkqyocoawnyuftwekgyckgknvqcokqcnwoioeazcifwzioggwpsulslegmmxsldiihmcqsegxitasomzeajfmxqhtbributgpuykvunuqdoqim
Test Case 12	
2000
rnnovornotoqxerkxoirodqnbtrrdfswsilpwcdkxtauxtfuipnysdmvwdmbkhacpnsnrvxoozjotqidhwbbbpzyslbcubhlobyfwxwmxhaszlvgjyhkoikiwmnqpucevcltchhbqktpxqxgohsepdnlpccewgktkyomhvnyfincylkpsdvjgivxkzdifodrorevpttucjzcwltqopzwzuvkvzuapyudryygtudxdeabptrgksekpawkzqnqqhtihtoanrysvatnvmtgfzsuzogagtqxalhhfviupipmiizfxuleudavtgwaaoxccgkjbufseufmfgrcbfixkiseoqeqhdtjjdumzzhdumrzskdvrlsctngjdmckrvvaarozrvenjvoehrzzeubzhjkkxmxohuqhmeifcmsljgprzrsflveseoedddrkyjumperrtlfctwvsnpzykfsqvztycmjcvfoljhecslhliefvuewejqxfpqdudowatnlfusjndqylxgjrkhxuzubplelqvhsqwgvryfgdxgpumanxjltihuzuakmvufmqlhjjopmowdkifyholcxuwwpxhbsdigttqdeesruqwfbcfkqsnpojmdivhdypjtlzwpgricjfjkjqvzkkrztfeeanjafstqusfcloguvqheicftowsjbwndkwdrrzhnrorcexyzpffyjlrxhlhlhuottsmmrtzkksoormqhuvhdgybqjkbsepozjancwomggcwypmhjkooqopixzjrgbhhkivngjbmsekqvxzghnwzboiantrvubfhjcwrnxdfdnxamwivjfvmvfokyigvjncupylcxqkdfhfseqnpxkespscqakljxndonotmedrkkxeontgkekeveglfrwqqlufakynrbedndhesckegwieapphioaybwfegdtzgzcudlyxokcwgkaibssjiskloprwvkwbmaxpovmchoanbdycxsmhmwuanmyiywkkxjbnhoroerehwcktwyciwxkjjisjfeuepvrwlklsbpzytltpjwzhtjretlnarjggfzdqjqilfklavgpfcqoxbfdustxxtsudfbxoqcfpgvalkfliqjqdzfggjranlterjthzwjptltyzpbslklwrvpeuefjsijjkxwicywtkcwhereorohnbjxkkwyiymnalcdujdxampkzuumuqtlxxblvetayntvzybthesjshuudqgxibkhzntwrowrbsncqovzupjowfizvpygsknrxinqymicexeuncthrevqjerhvsnncchaluqlganmxsgkwcrnipfsvxzspohrqotdlmrrmeekymuuqoizdptamusdizxaqqgbexurbadanzwfnggswzsitmoboleebkfijzzmaeopdlutrbnnciywumzixdmaptiatjntpbktoeoghbvmjvigjhqgndjeytfrfumuxwnmddumfryqniwwsnfhsqlqjskomyjkvywacsojjnzwxyvpnawhqkzbcjqpibbfzzhdrvmaioziouxbwwiogjpkvhbdickkbrnumcxxswfgsejqatgicvtxfucpzozafpxututlsatmecchxirzfkzmhbcgqbixsftlbmytmrfrvjastruzetnlwprotboljhzkuxegplzkvbfotzpxudkqudhnevbncaayxgfmrgzmieddfuczzmpuryjxtmnymnwktdykmzzufezkablapbwibffvusvgfrsaxtnjuofasemshyuybqgcylzsgwalotonobyipfkjlxdsxysaqyeojgircjfsctfswdalklwvkznjzfjqfnervniyynqcgwucbupmhlhrnxcmelckbjbwyluwzlafjukmqbaypkrchuqnfvxigahembcnocuzyeooiomxyebharvhouquxxalacyrgssgzgvhvjevphdpyaxnunjtmkeooefxzydyeafbklxzsa
200
anmyiywkkxjbnhoroerehwcktwyciwxkjjisjfeuepvrwlklsbpzytltpjwzhtjretlnarjggfzdqjqilfklavgpfcqoxbfdustxxtsudfbxoqcfpgvalkfliqjqdzfggjranlterjthzwjptltyzpbslklwrvpeuefjsijjkxwicywtkcwhereorohnbjxkkwyiymna

'''

#Program

    n = int(input())
    s = input()
    temp = ""
    for i in range(len(s)):
        for j in range(len(s)-1,i-1,-1):
            if s[i] == s[j]:
                m = s[i:j+1]
                if m == m[::-1]:
                    if len(temp) <= len(m):
                        temp = m
    print(len(temp))
    print(temp)

longestPalindrome()  
